# Generated by Django 2.0.6 on 2018-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_triggered', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('notebook', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('tag', models.CharField(max_length=40, null=True, blank=True)),
            ],
        ),
    ]
