# Generated by Django 2.0.7 on 2018-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='bypass_bozo',
            field=models.BooleanField(default=False),
        ),
    ]
